# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CgzzMesnK7WtF5VflAg8VMumrymW3CnW
"""

#My imports
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
import pandas as pd

#File Paths
CO2_emissions_fp = "https://docs.google.com/spreadsheets/d/1AlYAezgc_sYX5rnEUM1l-bljSOJ9Jx5UyhQP6mbAQ5o/export?format=csv"

imports_fp = "https://docs.google.com/spreadsheets/d/1rumraM_KipwQm5WKnA5UaQiLk-UrtMypxTvDPf2-gGI/export?format=csv"

lithium_production_fp = "https://docs.google.com/spreadsheets/d/1nkW9x0U6YlVeuorp3HIjdSb89jq8QdgNqUNEzN3ZZWs/export?format=csv"

safe_drinking_water_fp = "https://docs.google.com/spreadsheets/d/1N9BiMiL4yt15hPRLIFBgZhlVZncuuyi5tAI9WadiWuk/export?format=csv"

#Original Dataframes

df1 = pd.read_csv(CO2_emissions_fp)

df2 = pd.read_csv(imports_fp)

df3 = pd.read_csv(lithium_production_fp)

df4 = pd.read_csv(safe_drinking_water_fp)

"""# **Emissions**"""

dff = df1.copy()
dff

"""

dff = dff.drop('Code', axis = 1)
dff = dff[dff["Entity"].str.contains("Canada")==True]
dff = dff.set_index("Year")
dff = dff.drop(dff.index[0:213])

"""



dff

fig, ax = plt.subplots()
ax.plot(dff.index.values,dff["Annual CO₂ emissions (per capita)"])

fig, ax = plt.subplots()
ax.plot(dff.index.values,dff["Annual CO₂ emissions (per capita)"])
ax.set_ylabel("Canadian Carbon Emmisions")
ax.set_xlabel("Year")
ax.set_title("Canadian Carbon Emmisions")
ax.grid(which="major", axis='x', color='#DAD8D7', alpha=0.3)
ax.grid(which="major", axis='y', color='#DAD8D7', alpha=0.3)
ax.spines[['top','right','bottom','left']].set_visible(False)
plt.subplots_adjust(left=None, bottom=0.2, right=None, top=0.85, wspace=None, hspace=None)

"""# **Imports**"""

dfe = df2.copy()
dfe

#Cleaning Data

"""

dfe = dfe.drop('Seasonal adjustment', axis=1)
dfe = dfe.drop('GEO', axis=1)
dfe = dfe.drop('DGUID', axis=1)
dfe = dfe[dfe["Trade"].str.contains("Exports")==False]
dfe = dfe[dfe["UOM"].str.contains("Percent")==False]
dfe = dfe.drop('COORDINATE', axis=1)
dfe = dfe.drop("VECTOR", axis=1)
dfe = dfe.drop('STATUS', axis=1)
dfe = dfe.drop('SYMBOL', axis=1)
dfe = dfe.drop('DECIMALS', axis=1)
dfe = dfe.drop('TERMINATED', axis=1)
dfe = dfe[~dfe['Prices'].isin(['Chained (2012) dollars'])]
dfe = dfe[(dfe['Estimates'] == "Nuclear fuel and other energy products [C124]") | (dfe['Estimates'] == "Electronic and electrical equipment and parts [C18]")]
dfe = dfe.drop('UOM_ID', axis=1)
dfe = dfe.drop('SCALAR_ID', axis=1)
dfe = dfe.drop('Trade', axis=1)
dfe = dfe.drop('Prices', axis=1)
dfe["REF_DATE"] = dfe['REF_DATE'].str[:-3]
dfe = dfe.drop('Estimates', axis=1)
dfe = dfe.drop('UOM', axis=1)
dfe = dfe.drop('SCALAR_FACTOR', axis=1)
dfe = dfe.groupby('REF_DATE').sum()

"""



dfe

fig, ax = plt.subplots()
ax.plot(dfe.index.values,dfe["VALUE"])

fig, ax = plt.subplots()
ax.plot(dfe.index.values,dfe["VALUE"])
ax.set_ylabel("CAD (in millions)")
ax.set_xlabel("Year")
ax.set_title("Canadian Imports of Lithium and Lithium Powered Electronics")
ax.grid(which="major", axis='x', color='#DAD8D7', alpha=0.3)
ax.grid(which="major", axis='y', color='#DAD8D7', alpha=0.3)
ax.spines[['top','right','bottom','left']].set_visible(False)
plt.subplots_adjust(left=None, bottom=0.2, right=None, top=0.85, wspace=None, hspace=None)

"""# **Lithium Production**"""

dfr = df3.copy()
dfr

"""

dfr = dfr.drop('Code', axis = 1)
dfr = dfr[dfr["Entity"].str.contains("Chile")==True]
dfr = dfr.set_index("Year")
dfr = dfr.drop(dfr.index[0:17])

"""



dfr

fig, ax = plt.subplots()
ax.plot(dfr.index.values,dfr["Lithium Production-Reserves"])

fig, ax = plt.subplots()
ax.plot(dfr.index.values,dfr["Lithium Production-Reserves"])
ax.set_ylabel("CAD (in millions)")
ax.set_xlabel("Year")
ax.set_title("Canadian Imports of Lithium and Lithium Powered Electronics")
ax.grid(which="major", axis='x', color='#DAD8D7', alpha=0.3)
ax.grid(which="major", axis='y', color='#DAD8D7', alpha=0.3)
ax.spines[['top','right','bottom','left']].set_visible(False)
plt.subplots_adjust(left=None, bottom=0.2, right=None, top=0.85, wspace=None, hspace=None)

"""# **Safe Drinking Water**"""

dft = df4.copy()
dft

"""

dft = dft.drop('Code', axis = 1)
dft = dft[dft["Entity"].str.contains("Chile")==True]
dft = dft.set_index("Year")
dft = dft.drop(dft.index[0:12])

"""



dft

fig, ax = plt.subplots()
ax.plot(dft.index.values,dft["wat_sm_number_without"])

fig, ax = plt.subplots()
ax.plot(dft.index.values,dft["wat_sm_number_without"])
ax.set_ylabel("CAD (in millions)")
ax.set_xlabel("Year")
ax.set_title("Canadian Imports of Lithium and Lithium Powered Electronics")
ax.grid(which="major", axis='x', color='#DAD8D7', alpha=0.3)
ax.grid(which="major", axis='y', color='#DAD8D7', alpha=0.3)
ax.spines[['top','right','bottom','left']].set_visible(False)
plt.subplots_adjust(left=None, bottom=0.2, right=None, top=0.85, wspace=None, hspace=None)